### PR TITLE
print build url in show mode

### PR DESCRIPTION
**Pull request by kovetskiy**

### CODE REVIEW

**Comment by jszwedko** [comment]
:+1: I like adding the URL to the output, but what do you think about making it a separate line? I think this would make it more consistent with the key/value format of the rest of the build metadata.

**Comment by kovetskiy** [comment]
@jszwedko no need to do it in key-pair since this format is not for parsing in scripts, I think the current format is pretty good for reading.

**Comment by kovetskiy** [comment]
@jszwedko ping

**Comment by jszwedko** [comment]
Hi @kovetskiy 

Apologies for the delay. This change makes the current output look something like:

```
Build             66 https://circleci.com/gh/jszwedko/circleci-cli/66                                                                                                                                              
Subject           Merge pull request #13 from kovetskiy/feature-no-colors
Trigger           github
Author            Jesse Szwedko
Committer         GitHub
Status            success
Build Parameters  
                  None
Started           2017-09-27 16:26:44.946 +0000 UTC
Duration          1m6.653s
```

which I think is a bit messy, what do you think of:

```
Build             66
URL               https://circleci.com/gh/jszwedko/circleci-cli/66                                                                                                                                              
Subject           Merge pull request #13 from kovetskiy/feature-no-colors
Trigger           github
Author            Jesse Szwedko
Committer         GitHub
Status            success
Build Parameters  
                  None
Started           2017-09-27 16:26:44.946 +0000 UTC
Duration          1m6.653s
```

?

**Comment by kovetskiy** [comment]
@jszwedko I don't think this is a bit messy, I found it pretty good for reading. I don't see any point of adding new line for it. This format is not for machine parsing, only for humans reading. I'm using it for 10 days and it works for me.

**Comment by jszwedko** [comment]
I'd at least like to see it in `()`s to visualize separate it if we kept it on the same line, but are you opposed to separating it? I know that is only designed for human reading, but having it separate makes it easier to chain to `grep`, `cut`, etc. for one off one-liners. That is to say that I don't see the benefit of keeping it on the same line, but I do see a slight benefit in separating it.

I may be missing the benefit of keeping it on one line though 😄

**Comment by kovetskiy** [comment]
If you want to provide useful output for command line interacting, then you should output data in some parsable format like JSON.
If we will separate it to another line then one-line will looks like `circleci-ctl ... | awk '/^URL/{print $2}'`, right now it looks like `| awk '/^Build/{print $3}'`. Not so big improvement.

No need to add `()` around it, data separated by space already.

**Comment by jszwedko** [comment]
I appreciate your contribution and the idea of outputting the build URL in the `show` subcommand, but I would prefer that it appear as a separate line for visual clarity and consistency with the rest of the output.

**Pull request closed without merging**
